import pytest
import time
from tests.configTest import setup, select_store, franchiseStore, getElement
from pages.franchiseStorePages.homePage import HomePage
from selenium.webdriver.common.by import By

@pytest.mark.usefixtures("setup")
class Test_navigation_menu:


    def test_menu_order(self):
        select_store(self, franchiseStore)
        HomePage.articles_press(self)
        HomePage.orders_press(self)
        HomePage.orders_prepare_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia w przygotowaniu')]]"))
        HomePage.orders_press(self)
        HomePage.orders_sent_today_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia wysłane dzisiaj')]]"))
        HomePage.orders_press(self)
        HomePage.orders_pending_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia oczekujące')]]"))
        HomePage.orders_press(self)
        HomePage.orders_in_future_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia w przyszłość')]]"))
        HomePage.orders_press(self)
        HomePage.orders_generated_for_today_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia wygenerowane na dziś')]]"))
        HomePage.orders_press(self)
        HomePage.orders_summary_pending_press(self)
        assert getElement(self, (By.CSS_SELECTOR, "[value^='Zamknij']"))
        getElement(self, (By.CSS_SELECTOR, "[value^='Zamknij']")).click()
        time.sleep(0.5)
        HomePage.orders_press(self)
        HomePage.orders_sent_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia wysłane')]]"))
        HomePage.orders_press(self)
        HomePage.orders_accept_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia zaakceptowane')]]"))
        HomePage.orders_press(self)
        HomePage.orders_realized_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia zrealizowane')]]"))
        HomePage.orders_press(self)
        HomePage.orders_unrealized_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia niezrealizowane')]]"))
        HomePage.orders_press(self)
        HomePage.orders_rejected_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia odrzucone')]]"))
        HomePage.orders_press(self)
        HomePage.orders_all_sent_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zamówienia wszystkie złożone')]]"))
        HomePage.orders_press(self)
        HomePage.orders_scanner_out_of_stock_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'BRAKI - DOSTĘPNE PLIKI SKANERA')]]"))
        HomePage.orders_press(self)
        HomePage.orders_scanner_automatic_out_of_stock_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Braki automatyczne')]]"))
        HomePage.orders_press(self)
        HomePage.orders_scanner_orders_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'ZAMÓWIENIE - DOSTĘPNE PLIKI SKANERA')]]"))
        HomePage.orders_press(self)
        HomePage.orders_scanner_log_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'DZIENNIK ZDARZEŃ')]]"))
        HomePage.orders_press(self)
        HomePage.orders_menu_report_S001_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'LISTA RAPORTÓW - SPRZEDAŻ TOWARÓW WG WARTOŚCI SPRZEDAŻY (S001)')]]"))
        HomePage.orders_press(self)
        HomePage.orders_menu_report_S002_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'LISTA RAPORTÓW - RAPORT STRATY ZNANEJ (S002)')]]"))
        HomePage.orders_press(self)
        HomePage.orders_menu_report_M013_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'LISTA RAPORTÓW - STANY MAGAZYNOWE NA DZIEŃ Z KARTY MAGAZYNOWEJ (M013)')]]"))
        HomePage.orders_press(self)
        HomePage.orders_menu_report_T011_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'LISTA RAPORTÓW - RAPORT - ASORTYMENT NIEEFEKTYWNY (T011)')]]"))
        HomePage.orders_press(self)
        HomePage.orders_menu_select_other_report(self, False)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'LISTA RAPORTÓW')]]"))
        getElement(self, (By.CSS_SELECTOR, "[value^='Zamknij']")).click()
        time.sleep(0.5)
        HomePage.orders_press(self)
        HomePage.orders_menu_report_top_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'STATYSTYKI SPRZEDAŻY DLA SKLEPU')]]"))
        HomePage.orders_press(self)
        HomePage.orders_desktop_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Statystyki sklepu')]]"))

    def test_home_page_menu(self):
        select_store(self, franchiseStore)
        HomePage.articles_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Statystyki sklepu')]]"))
        HomePage.homepage_press(self)
        HomePage.contractors_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Faktury')]]"))
        HomePage.homepage_press(self)
        HomePage.communication_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Mail')]]"))
        HomePage.homepage_press(self)
        HomePage.eplanus_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'DOKUMENTY')]]"))
        HomePage.homepage_press(self)
        HomePage.top_report_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'STATYSTYKI SPRZEDAŻY DLA SKLEPU')]]"))
        HomePage.homepage_press(self)
        HomePage.tools_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Operacje ręczne')]]"))
        HomePage.homepage_press(self)
        HomePage.administration_store_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Kalendarz dni wolnych sklepu')]]"))
        HomePage.homepage_press(self)
        HomePage.administration_users_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Dodaj nowego użytkownika')]]"))
        HomePage.homepage_press(self)
        HomePage.cart_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'ZAWARTOŚĆ KOSZYKA/TYMCZASOWEJ LISTY TOWARÓW')]]"))
        HomePage.homepage_press(self)
        HomePage.change_password_press(self)
        assert getElement(self, (By.XPATH, "//*[text()[contains(.,'Zmiana hasła')]]"))

    

